### ISSUE TITLE
Configurable background color

### ISSUE THREAD

**Issue by hymie0** [chubin/wttr.in#200]
## TODO

* [x] background for PNG images
* [ ] background for HTML
* [ ] background for ANSI

Background must be specified using parameter `background=`

## Details

I just want to say that this is awesome.

However, the color scheme expects the terminal to be black, and I prefer a white screen.  I can't see some of the pictures or the temperature because it draws bright-yellow characters on the white background.

Can you create an option to specify "white background, use other colors" ?

**Comment by dmgr** [comment]
It would be nice if there were an option to set a background color of your choice. Then you would be able to show a weather on a black background despite you have a white background terminal.

**Comment by chubin** [comment]
It is a good idea, it is related to #425

**Comment by midzer** [comment]
*bump*

**Comment by chubin** [comment]
@midzer you want to have it for PNG or for the terminal?

**Comment by midzer** [comment]
@chubin I think it might come handy for light websites using wttr-switcher, so PNG

**Comment by chubin** [comment]
@midzer PNG Images background configuration parameter was added. You can configure it with `background=`, e.g.:

https://wttr.in/Munich_background=007777.png

**Comment by midzer** [comment]
When I set white background, ie https://wttr.in/Munich_background=FFFFFF.png, the font is very light and almost not readable.

**Comment by chubin** [comment]
Try to use inverted colors for foreground:  https://wttr.in/Munich_I_background=FFFFFF.png
