### ISSUE TITLE
Basque translation 💃

### ISSUE THREAD

**Issue by chubin** [chubin/wttr.in#438]
# TODO

* [X] lib/translations.py
* [X] share/translations/eu.txt
* [X] help: share/translations/help-eu.txt
* [ ] v2 translation
* [X] we-lang translation

**Comment by chubin** [comment]
@isagasti

I am staring with welang translation.
Is this correct:
```
Goizean.
Eguerdia.
Arratsaldean.
Gaua.
```
?

**Comment by isagasti** [comment]
Great,

It's not correct

"eu":{"Goiz", "Eguerdi",      "Arratsalde",    "Gau" },

Or it can be (if you want to add the article, "morning" vs "the morning"): 
"eu":{"Goiza", "Eguerdia",      "Arratsaldea",    "Gaua" },

But I think you should use the first one.

And the spanish version you should also correct it. The correct translation is:

"es":{"Mañana", "**Mediodía**",      "Tarde",    "Noche" },

**Comment by chubin** [comment]
I've started the translation, and activated it on wttr.in.

Please check:

https://eu.wttr.in/

Now let's go to the next step. Could you take a look at `lib/translations.py`?

**Comment by isagasti** [comment]
Working on the translation, project forked

**Comment by isagasti** [comment]
Translations finished. Let me know if something is missing.

**Comment by chubin** [comment]
@isagasti Iker, thank you for the translation! Where is it? Do you plan to do a Pull-Request? (it would be the best)

**Comment by isagasti** [comment]
Sorry, it was my fault, PR done ;)
https://github.com/chubin/wttr.in/pull/443

**Comment by chubin** [comment]
I've merged it, please test:

https://eu.wttr.in

I see that you've missed some messages in `lib/translations.py`:

* `UNKNOWN_LOCATION`
* `LOCATION`
* `NOT_FOUND_MESSAGE`
* `FOLLOW_ME`
* `CAPTION`

**Comment by chubin** [comment]
Maybe we should use `/bio` as an airport-code query example in the basque translation of help instead of `/muc`?

**Comment by chubin** [comment]
Iker, I added your name to http://wttr.in/:translation
If you want to hide it (or replace with a pseudonym) please say

**Comment by isagasti** [comment]
You have a new Pull-Request with some improvements and your suggestions. Thanks for the credits.

**Comment by chubin** [comment]
I've merged it. Perfect! Now we have almost everything translated.
The last one:

https://github.com/chubin/wttr.in/blob/master/lib/translations_v2.py

Just one line

**Comment by isagasti** [comment]
Hi @chubin 

I told you that welang translation wrong:
The correct translation is:
"eu":{"Goiza", "Eguerdia", "Arratsaldea", "Gaua" },

Could you please correct it? I dont know how to do it.

**Comment by chubin** [comment]
It was correct in the code (you corrected it); it was just not deployed, but now it is:

https://eu.wttr.in/Munich

**Comment by isagasti** [comment]
Hi @chubin 
Is something else missing? Can we close the issue? :)

**Comment by chubin** [comment]
The last one is the v2 translation, but it is only one line:

https://github.com/chubin/wttr.in/blob/master/lib/translations_v2.py

**Comment by chubin** [comment]
@isagasti 
Let's make the last step and finalize the Basque translation.

Google translation of the v2:
```
"Eguraldia", "Ordu-eremua", "Orain", "Egunsentia", "Eguzkia", "Zenit", "Ilunabarra", "Ilunabarra"
("Weather",  "Timezone",     "Now",      "Dawn",             "Sunrise",      "Zenith",       "Sunset",           "Dusk")
```

Is it correct, or some words are wrong?

**Comment by chubin** [comment]
I've added the translation from the last comment (for v2). Hopefully it is correct, if not please just let me know.
Now I close the issue. The Basque translation is done. Thank you very much for the help!
