### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by chubin** [chubin/wttr.in#533]
We already have some Spanish translation (see #289 for example), but according to @amadeogarcia it is not full.

Let us go through the list and fix missing parts.

## Todo

* [ ] lib/translations.py
* [ ] share/translations/es.txt
* [ ] help: share/translations/help-es.txt
* [ ] v2 translation
* [ ] we-lang translation

**Comment by chubin** [comment]
`lib/translations.py` is fixed with the merge.
