### ISSUE TITLE
Amharic translation

### ISSUE THREAD

**Issue by chubin** [chubin/wttr.in#565]
At the moment, the translation pieces are scattered over the project.
We are working on bringing all of them together, but until that translation
must be done in several files.

@rkassa please help with the translation.

## Todo

* [ ] lib/translations.py
* [ ] share/translations/es.txt
* [ ] help: share/translations/help-es.txt
* [ ] v2 translation
* [ ] we-lang translation

**Comment by chubin** [comment]
@rkassa If you want, you can simply post translations here, but better of course, if you make afork, and then a pull-request; you can make pull-requests after each small portion of translation, as you like it.
